version: "3.3"
services:
  rpi-spotify-no-normalize:
    build: .
    image: tillbill/rpi-spotify-no-normalize
    network_mode: host
    devices:
      - "/dev/snd:/dev/snd"
    environment:
      - SPOTIFY_NAME=MySpeaker
  
